# Основные модули и пакеты
TOP_MODULE  = top.sv
TB_PKG      = apb_pkg.sv

DUT_VARIANT = master

# Определения тестов и количества запусков (<имя_теста>:<количество_запусков>)
TESTS = simple_test:1 

include ../common.mk